### ISSUE TITLE
Negative value conversions

### ISSUE THREAD

**Issue by jps-aldridge** [BrunoB81HK/PyNAU7802#1]
The NAU7802 returns its readings in 3 byte, two's complement format. The code in getReading() is converting negative values as if they are sign & magnitude, with the result that negative values are returned wrongly. The following change seems to do the trick:

Replace

        sign = value_list[0] >> 7  # Recover the sign bit if 0 -> +, if 1 -> -
        value = value_list[0] << 16 & 0x7FFFFF  # The 0x7FFFFF remove the sign bit
        value |= value_list[1] << 8 & 0xFFFF
        value |= value_list[2] & 0xFF

        if sign == 1:  # Change the sign according to the bit
            value = -value

with

        value = int.from_bytes(value_list, byteorder='big', signed=True)

I note that this method is documented as new in Python 3.2, so another technique will be needed if support for earlier versions is desired.

**Comment by BrunoB81HK** [comment]
Thanks a lot for the tip! The changes should be applied soon!

Have a nice day,

Bruno
