### ISSUE TITLE
Python run

### ISSUE THREAD

**Issue by catalinalb** [BrunoB81HK/PyNAU7802#5]
Hello,

What is the next step after installing the pip install PyNAU7802 ? 
How to start the thing? 
In documentation is only about Arduino. I am connected to the raspbery pi....

Thank you

**Comment by BrunoB81HK** [comment]
Hi!

Thank you for using PyNAU7802.

Was the `pip install PyNAU7802` command successful? If so, the next step would be to create a python file in your project directory and copy the example script from this repo's [README.md](https://github.com/BrunoB81HK/PyNAU7802#example).

Once done, you can run the file and, assuming you wired the sensor correctly, everything should work fine. If so, you can modify the script to fit the needs of your project.

This package is based on SparkFun's [Qwiic Scale - NAU7802](https://www.sparkfun.com/products/15242). The functions of the package should match those for the [Arduino library](https://github.com/sparkfun/SparkFun_Qwiic_Scale_NAU7802_Arduino_Library). The main difference would be at the setup stage. For example, [this Arduino sketch](https://github.com/sparkfun/SparkFun_Qwiic_Scale_NAU7802_Arduino_Library/blob/master/examples/Example1_BasicReadings/Example1_BasicReadings.ino) would look like this with PyNAU7802:

```python
# Import the required libraries
from smbus2 import SMBus
from PyNAU7802 import NAU7802

bus = SMBus(1)  # Create an instance of the I2C bus
myScale = NAU7802()  # Create instance of the NAU7802 class

# Setup
print("Qwiic Scale Example")

if not myScale.begin(bus):
    print("Scale not detected. Please check wiring. Freezing...")
    exit(1)

print("Scale detected!")

# Loop
while True:
    if myScale.available():
        currentReading = myScale.getReading()
        print(f"Reading: {currentReading}")

```

I will try to convert the Ardunio examples soon.

Another useful page is SparkFun's [Qwiic Scale Hookup Guide](https://learn.sparkfun.com/tutorials/qwiic-scale-hookup-guide)

If you're still lost and need more guidance, feel free to share what you expect to do in your project and I'll try to help you as good as I can.

**Comment by catalinalb** [comment]
I did it :) 

Thanks 👍
